name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      #fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    
    env:
      CONAN_USER_HOME: "~/conan/"
    
    steps:
    - uses: actions/checkout@v2

    - name: Check Python
      run: python --version

    - name: Make Conan dir
      run: mkdir conan
      
    - name: Get Conan
      run: |
        pip3 install wheel setuptools
        pip3 install conan --upgrade
        
    - name: Fix Path on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: echo "::add-path::/home/runner/.local/bin"

    - name: Check Conan
      run: conan --version

    - name: Add bincrafters remote
      run: conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"

    - name: Check CMake
      run: cmake --version
        
    - name: Configure build
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
  
    - name: Build
      run: cmake --build build
