name: CI

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]

    runs-on: ${{ matrix.os }}
    
    env:
      CONAN_USER_HOME: "${{ github.workspace }}/conan/"

    steps:
    - uses: actions/checkout@v2

#    - name: New Cache Conan modules
#      if: matrix.os == 'ubuntu-latest'
#      id: new-cache-conan
#      uses: turtlebrowser/conan-cache@master
#      with:
#          bot_name: turtlebrowser-bot
#          bot_token: ${{ secrets.CACHE_REPO_TOKEN }}
#          cache_name: turtlebrowser/conan-cache-linux
#          key: host-${{ runner.os }}-target-${{ runner.os }}-${{ hashFiles('conanfile.py') }}
#          target_os: ${{ runner.os }}

#    - name: Set CONAN_USER_HOME ownership to current user
#      run: sudo chown -R $(id -u):$(id -g) ${{ env.CONAN_USER_HOME }}

    - name: Cache Conan modules
      id: cache-conan
      uses: actions/cache@v1
      env:
        cache-name: cache-conan-modules
      with:
        path: ${{ env.CONAN_USER_HOME }}
        key: ${{ runner.os }}-builder-${{ env.cache-name }}-${{ hashFiles('conanfile.py') }}
        restore-keys: ${{ runner.os }}-builder-${{ env.cache-name }}-

#    - name: Check size
#      run: du -h -d1 ${{ env.CONAN_USER_HOME }}/.conan/data/qt/5.14.2/bincrafters/stable
           
    - name: Get Conan
      run: |
        pip3 install wheel setuptools
        pip3 install conan --upgrade
        
    - name: Fix Path on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: echo "::add-path::/home/runner/.local/bin"

    - name: Get Conan Dependencies
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..

    - name: Clean up Conan
      run: |
        conan remove -f "*" --builds
        conan remove -f "*" --src
        conan remove -f "*" --system-reqs

#    - name: Check size
#      run: du -h -d1 ${{ env.CONAN_USER_HOME }}/.conan/data/qt/5.14.2/bincrafters/stable
  
    - name: Build
      run: cmake --build build
