# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    
    env:
      CONAN_USER_HOME: "~/conan/"
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Check Python
      run: |
        python --version

    - name: Make Conan dir
      run: mkdir conan
      
    - name: Get Conan
      run: |
        pip3 install wheel setuptools
        pip3 install conan --upgrade
        
    - name: Fix Path on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo $PATH
        ls /home/runner/.local/bin
      #export PATH=$PATH:/home/runner/.local/bin

    - name: Check Conan
      run: |
        conan --version

    - name: Add bincrafters remote
      run: |
        conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"

    - name: Check CMake
      run: |
        cmake --version
        
    - name: Configure build
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
  
    - name: Build
      run: cmake --build build

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
