name: Update Conan

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '50 11 * * 0'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    env:
      CONAN_USER_HOME: "${{ github.workspace }}/release"
      CONAN_USER_HOME_SHORT: "${{ github.workspace }}/release/short"
      CONAN_SYSREQUIRES_MODE: enabled
      INSTALL_DIR: ${{ github.workspace }}/install/

    steps:
    - uses: actions/checkout@v2

    - name: Cache Conan modules
      id: cache-conan
      uses: turtlebrowser/conan-cache@master
      with:
          bot_name: turtlebrowser-bot
          bot_token: ${{ secrets.CACHE_REPO_TOKEN }}
          cache_name: turtlebrowser/conan-cache-turtlebrowser
          key: host-${{ runner.os }}-target-${{ runner.os }}-update-${{ github.run_number }}
          target_os: ${{ runner.os }}
          lfs_limit: 60

    - name: Get Conan
      run: |
        pip3 install wheel setuptools
        pip3 install conan --upgrade
        mkdir build
        
    - name: Fix Path on Ubuntu
      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-latest'
      run: echo "::add-path::/home/runner/.local/bin"
      
    - name: Add System Dependency
      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-latest'
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get build-dep qt5-default
        sudo apt install libgl1-mesa-dev
        sudo apt install libx11-xcb-dev
        sudo apt install libfontenc-dev
        sudo apt install libxaw7-dev
        sudo apt install libxcomposite-dev
        sudo apt install libxcursor-dev
        sudo apt install libxdamage-dev
        sudo apt install libxi-dev
        sudo apt install libxinerama-dev
        sudo apt install libxmuu-dev
        sudo apt install libxrandr-dev
        sudo apt install libxres-dev
        sudo apt install libxss-dev
        sudo apt install libxtst-dev
        sudo apt install libxv-dev
        sudo apt install libxvmc-dev
        sudo apt install libxxf86vm-dev
          
#    - name: Add System Dependency
#      if: matrix.os == 'ubuntu-20.04' || matrix.os == 'ubuntu-latest'
#      run: apt install libgl1-mesa-dev

    - name: Remove all previous builds
      if: matrix.os == 'macos-latest'
      run: conan remove -f "*"

    - name: Get Conan Dependencies
      working-directory: build
      run: cmake -DUPDATE_CONAN=ON -DCMAKE_BUILD_TYPE=Release ..

    - name: Clean up Conan
      run: |
        conan remove -f "*" --builds
        conan remove -f "*" --src
        conan remove -f "*" --system-reqs
