name: FreeBSD

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 17 * * 0'

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: A job to run test FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.0.9
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y cmake py37-pip
        run: |
          pip3 install wheel setuptools
          pip3 install conan --upgrade
          cmake -E make_directory ${{runner.workspace}}/build
          cd ${{runner.workspace}}/build && cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release
          cd ${{runner.workspace}}/build && cmake --build . --config Release
