name: FreeBSD

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '50 22 * * 0'

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: Test building TurtleBrowser in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.0.9
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y cmake conan python2 sudo gmake
        run: python=python2 && cmake -E make_directory ${{runner.workspace}}/build && cd ${{runner.workspace}}/build && cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=gmake && cmake --build . --config Release
