name: Update Licenses

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '40 15 * * 6'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: macos-latest
          PLATFORM_NAME: macos

        - os: ubuntu-latest
          PLATFORM_NAME: linux

        - os: windows-latest
          PLATFORM_NAME: windows

    runs-on: ${{ matrix.os }}
    
    env:
      CONAN_USER_HOME: "${{ github.workspace }}/release"
      CONAN_USER_HOME_SHORT: "${{ github.workspace }}/release/short"
      CONAN_SYSREQUIRES_MODE: enabled
      INSTALL_DIR: ${{ github.workspace }}/install/
      RELATIVE_LICENSE_PATH: src/resources/licenses/${{matrix.PLATFORM_NAME}}/
      FULL_LICENSE_PATH: ${{ github.workspace }}/src/resources/licenses/${{matrix.PLATFORM_NAME}}/
      QRC_FILE_NAME: ${{matrix.PLATFORM_NAME}}_licenses.qrc

    steps:
    - uses: actions/checkout@v2

    - name: Cache Conan modules
      id: cache-conan
      uses: turtlebrowser/conan-cache@master
      with:
          bot_name: turtlebrowser-bot
          bot_token: ${{ secrets.CACHE_REPO_TOKEN }}
          cache_name: turtlebrowser/conan-cache-turtlebrowser
          key: host-${{ runner.os }}-target-${{ runner.os }}-update-${{ github.run_number }}
          target_os: ${{ runner.os }}
          lfs_limit: 60

    - name: Get Conan
      run: |
        pip3 install wheel setuptools
        pip3 install conan --upgrade
        mkdir build
        
    - name: Fix Path on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: echo "::add-path::/home/runner/.local/bin"

    - name: Build licenses
      working-directory: build
      run: cmake -DCHECK_IN_LICENSES=ON -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} -DCMAKE_BUILD_TYPE=Release ..

    - name: Clean licenses
      run: |
        rm -rf ${{ env.FULL_LICENSE_PATH }}
        mkdir ${{ env.FULL_LICENSE_PATH }}

    - name: Install licenses
      working-directory: build
      run: cmake --build . --config Release --target install

    - name: Clean licenses
      run: | 
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.cpp" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.h" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.cc" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.py" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.pyc" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.pl" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.pl.vanilla" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.js" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*,js" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.json" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.pro" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.qrc" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.png" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.qdoc" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.yml" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.patch" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "*.ini" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "CHANGELOG.md" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "README.md" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name ".npmignore" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name ".eslintignore" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "license-checker" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "nopt" -exec rm {} +
        find ${{ env.RELATIVE_LICENSE_PATH }}/licenses -type f -name "OWNERS" -exec rm {} +

    - name: Make qrc
      working-directory: ${{ env.RELATIVE_LICENSE_PATH }}
      run: |
        touch ${{ env.QRC_FILE_NAME }}
        echo '<RCC><qresource prefix="/">' >> ${{ env.QRC_FILE_NAME }}
        find licenses -type f -exec echo "<file>{}</file>" \; >>  ${{ env.QRC_FILE_NAME }}
        echo '</qresource></RCC>' >> ${{ env.QRC_FILE_NAME }}
        
    - name: Commit qrc
      working-directory: ${{ env.RELATIVE_LICENSE_PATH }}
      run: |
        git add ${{ env.QRC_FILE_NAME }}
        git commit -m "Updated qrc file"
      
    - name: Commit licenses
      working-directory: ${{ env.RELATIVE_LICENSE_PATH }}
      run: |
        git add -A .
        git commit -m "Updated license files"
